max_pseudoliberties: max_pseudoliberties.c
	gcc -O3 -std=c99 -Wall max_pseudoliberties.c -o max_pseudoliberties

max_pseudoliberties2: max_pseudoliberties2.c
	gcc -O3 -std=c99 -Wall max_pseudoliberties2.c -o max_pseudoliberties2

max_pseudoliberties3: max_pseudoliberties3.c
	gcc -O3 -std=c99 -Wall max_pseudoliberties3.c -o max_pseudoliberties3
