max_liberties: max_liberties.c
	gcc -O3 -std=c99 -Wall max_liberties.c -o max_liberties

max_liberties2: max_liberties2.c
	gcc -O3 -std=c99 -Wall max_liberties2.c -o max_liberties2

max_liberties3: max_liberties3.c
	gcc -O3 -std=c99 -Wall max_liberties3.c -o max_liberties3
