maxstrings: maxstrings.c
	gcc -O3 -std=c99 -Wall maxstrings.c -o maxstrings

maxstrings2: maxstrings2.c
	gcc -O3 -std=c99 -Wall maxstrings2.c -o maxstrings2

maxstrings3: maxstrings3.c
	gcc -O3 -std=c99 -Wall maxstrings3.c -o maxstrings3

